// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBovIZ_gFilgHeal5XZ7C3OfBuEf6X4ltU',
    appId: '1:664288690321:web:c89862e04046245e48ff30',
    messagingSenderId: '664288690321',
    projectId: 'key2rightpro',
    authDomain: 'key2rightpro.firebaseapp.com',
    storageBucket: 'key2rightpro.appspot.com',
    measurementId: 'G-6QNXJLKYPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz0MJz4-59LseHXUyQWXaKIJkN2TCdgEY',
    appId: '1:664288690321:android:b810cecdfcf3b0c148ff30',
    messagingSenderId: '664288690321',
    projectId: 'key2rightpro',
    storageBucket: 'key2rightpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSJFTuYMH9CokQ5h5Gi1g4DunSsr1S_Lg',
    appId: '1:664288690321:ios:167a8690b5a7582848ff30',
    messagingSenderId: '664288690321',
    projectId: 'key2rightpro',
    storageBucket: 'key2rightpro.appspot.com',
    iosBundleId: 'com.example.key2rights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSJFTuYMH9CokQ5h5Gi1g4DunSsr1S_Lg',
    appId: '1:664288690321:ios:6c1967e7e544198648ff30',
    messagingSenderId: '664288690321',
    projectId: 'key2rightpro',
    storageBucket: 'key2rightpro.appspot.com',
    iosBundleId: 'com.example.key2rights.RunnerTests',
  );
}
